---
# Create oracle user and groups
- name: create Oracle groups and user 
  action: group name=dba
- action: group name=admin
- action: group name=oinstall
- action: group name=vboxsf
# Note that post install oracle may get moved to /app/oracle as part of the DSS/Demo standard
# This will create a home dir that can be used for the initial setup
#  - action: user name=oracle createhome=yes groups=dba,admin,oinstall,vboxsf home=$oracleuser_home
# Create demo home, paths, etc. 
- action: file dest=$demo_root state=directory
- action: file dest=$demo_home state=directory owner=oracle
- action: file dest=$demo_home/users state=directory owner=oracle
- action: file dest=/app/oracle/product state=directory owner=oracle
- action: file dest=$mw_home state=directory owner=oracle
- action: file dest=$oracle_home state=directory
