#!/bin/sh
if [[ $# -lt 2 ]];then
	exit 1
fi
day1=$1
day2=$2
if [[ $day1 -gt $day2 ]];then
	tmpd=$day1
	day1=$day2
	day2=$tmpd
fi

y1=`echo $day1|awk '{print substr($1,1,4)}'`
y2=`echo $day2|awk '{print substr($1,1,4)}'`
m1=`echo $day1|awk '{print substr($1,5,2)}'`
m2=`echo $day2|awk '{print substr($1,5,2)}'`
d1=`echo $day1|awk '{print substr($1,7,2)}'`
d2=`echo $day2|awk '{print substr($1,7,2)}'`

days=0
i=`expr $y1 + 1`
while [[ $i -lt $y2 ]];do
	if [[ `expr $i % 4` == 0 ]];then
		days=`expr $days + 366`
	else
		days=`expr $days + 365`
	fi
	i=`expr $i + 1`	
done

tmpy1=$y1
tmpy2=$y2
tmpm=$m1
if [[ $y2 -gt $y1 ]];then
	tmpy2=`expr $y1 + 1`
fi
while [[ $tmpy1 -lt $tmpy2 || $tmpm -lt $m2 ]];do
	monthlastday=31
	if [[ $tmpm == "04" || $tmpm == "06" || $tmpm == "09" || $tmpm == "11" ]];then
		monthlastday=30
	elif [[ $tmpm == "02" ]];then
		if [[ `expr $tmpy1 % 4` == 0 ]];then
			monthlastday=29
		else 
			monthlastday=28
		fi
	fi
	if [[ $tmpm == $m1 && $tmpy1 == $y1 ]];then
		days=`expr $days + $monthlastday - $d1`
	else
		days=`expr $days + $monthlastday`
	fi
	tmpm=`expr $tmpm + 1`
	if [[ $tmpm -gt 12 ]];then
		tmpm=1
		tmpy1=`expr $tmpy1 + 1`
	fi
	if [[ $tmpm -lt 10 ]];then
		tmpm="0"$tmpm
	fi
done
if [[ $y1 -lt $y2 || $m1 -lt $m2 ]];then
	days=`expr $days + $d2`
else 
	days=`expr $days + $d2 - $d1`
fi

echo $days
