#!/bin/sh

if [[ -f ~/.profile ]];then
	. ~/.profile
elif [[ -f ~/.bash_profile ]];then
	. ~/.bash_profile
fi

if [[ "$ORACLE_SID" == "" || "$ORACLE_HOME" == "" ]];then
	echo "Oracle_Envierments_Not_Set"
	exit 1
fi
INST_VERSION=`echo 'select version from v$instance; '|sqlplus -s "/as sysdba"|awk '{if(NF>0)print}'|tail -1`
if [[ "$INST_VERSION" != "" ]];then
   main_version=`echo $INST_VERSION|awk '{print $1}' FS='.'`
   if [[ "$main_version" == '9' ]];then
      sqlplus -s "/as sysdba" <<!|awk '{if(NF>=14)print}'|sed 's/  */ /g'
	set heading off
	set lines 9999
	set pages 9999 
	set feedback off
	set serveroutput off
       select nvl(p.SPID,-1) pid, s.STATUS,s.SID, s.SERIAL# serial, nvl(s.USERNAME,'unknown') dbuser, 
              s.COMMAND cmdtype, to_char(s.LOGON_TIME,'yymmddhh24miss') logon_time, s.LAST_CALL_ET,
	      nvl(s.MACHINE,'unknown') machine, nvl(s.OSUSER,'unknown') osuser, replace(nvl(s.PROGRAM,'unknown'),' ','_') program, 
              nvl(s.SQL_HASH_VALUE,-1) hash_value, 'unknown' SQL_ID,
               nvl(replace(w.EVENT,' ','_'),'unknown') event, nvl(w.SECONDS_IN_WAIT,'-1') seconds_in_wait, 
              nvl(w.WAIT_TIME,'-1') wait_time, replace(nvl(w.STATE,'unknown'),' ','_') wait_state, nvl(w.p1, -1),
	      decode(w.event,'latch free',(select replace(nvl(name,'unknown'),' ','_') from v\$latch where latch#=w.p2), nvl(p2,-1) ),
              nvl(w.p3, -1), nvl((select sql_text from v\$sqlarea where hash_value=s.sql_hash_value),'unknown')
       from v\$session s, v\$process p, v\$session_wait w 
       where s.SID=w.SID(+) and s.PADDR=p.ADDR(+) and s.TYPE='USER' and s.USERNAME is not null and s.status='ACTIVE'
;
!
   else 
      sqlplus -s "/as sysdba" <<!|awk '{if(NF>=14)print}'|sed 's/  */ /g'
        set heading off
        set lines 9999
        set pages 9999
        set feedback off
        set serveroutput off
       select nvl(p.SPID,-1) pid, s.STATUS,s.SID, s.SERIAL# serial, nvl(s.USERNAME,'unknown') dbuser, 
              s.COMMAND cmdtype, to_char(s.LOGON_TIME,'yymmddhh24miss') logon_time, s.LAST_CALL_ET,
              nvl(s.MACHINE,'unknown') machine, nvl(s.OSUSER,'unknown') osuser, replace(nvl(s.PROGRAM,'unknown'),' ','_') program, 
              nvl(s.SQL_HASH_VALUE,-1) hash_value, nvl(s.SQL_ID,'unknown') SQL_ID,
              nvl(replace(w.EVENT,' ','_'),'unknown') event, nvl(w.SECONDS_IN_WAIT,'-1') seconds_in_wait, 
              nvl(w.WAIT_TIME,'-1') wait_time, replace(nvl(w.STATE,'unknown'),' ','_') wait_state, nvl(w.p1, -1),
              decode(w.event,'latch free',(select replace(nvl(name,'unknown'),' ','_') from v\$latch where latch#=w.p2), nvl(p2,-1) ),
              nvl(w.p3, -1), nvl((select sql_text from v\$sqlarea where hash_value=s.sql_hash_value),'unknown')
       from v\$session s, v\$process p, v\$session_wait w
       where s.SID=w.SID(+) and s.PADDR=p.ADDR(+) and s.TYPE='USER' and s.USERNAME is not null and s.status='ACTIVE'
;
!
   fi
fi
